### ISSUE TITLE
Change addProperty to overwriteProperty

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/chai-bn#1]
https://github.com/ZeppelinSolutions/chai-bn/blob/4c036a28bd5b5b3e7273199b9520ce788ab1a51d/chai-bn.js#L118

https://github.com/ZeppelinSolutions/chai-bn/blob/4c036a28bd5b5b3e7273199b9520ce788ab1a51d/chai-bn.js#L131

See [`overwriteProperty`](https://www.chaijs.com/api/plugins/#method_overwriteproperty).

**Comment by nventuro** [comment]
Fixed in 2c9ce2b36f3f4a8c4af0f26aeda230074e5fcca8

**Comment by frangio** [comment]
By the way you can get GitHub to automatically close this by adding "Fixes #1" in the commit description, just as we do with PRs.

**Comment by nventuro** [comment]
I know, but I fixed those issues before I knew you opened issues here 😅
