### ISSUE TITLE
Use stricter type checking

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/chai-bn#2]
The `isBN` function is implemented with duck typing and it should only use the stricter `instanceof`.

https://github.com/ZeppelinSolutions/chai-bn/blob/4c036a28bd5b5b3e7273199b9520ce788ab1a51d/chai-bn.js#L15-L19

**Comment by nventuro** [comment]
Fixed in 737cb97dd806215358e86f674067f0de153e18d8
